[package]
name = "peerchat"
version = "0.1.0"
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]

[dependencies]
serde = "*"
serde_json = "*"
serde_derive = "*"
log = "0.3"
env_logger = "0.4" # default feature requires regex
